#!/usr/bin/env python
""" Main module.

"""
import argparse
from os import path
from code.analyzer import CodeAnalyzer


parser = argparse.ArgumentParser(description='Python to bash trans-compiler.')
parser.add_argument('file', metavar='script', type=str,
    help='program read from script file')

def print_error(msg):
    print('sherlock: error: %s' % msg)

def main():
    args = parser.parse_args()
    try:
        if path.isfile(args.file):
            script = ''
            with open(args.file) as f:
                script = f.read()
            analyzer = CodeAnalyzer(script)
            generator = analyzer.analysis()
            generator.generate()
        else:
            print_error("can't open file '%s'" % args.file)
    except IOError:
        print_error("can't open file '%s'" % args.file)


if __name__ == '__main__':
    main()
